# Generated by Django 5.1.4 on 2024-12-13 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=50)),
                ('contrasenia', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Filtro',
            fields=[
                ('inicio_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gestion.inicio')),
                ('numero_filtro', models.SmallIntegerField()),
                ('nota', models.CharField(max_length=255)),
            ],
            bases=('gestion.inicio',),
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('inicio_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gestion.inicio')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('DNI', models.CharField(max_length=13)),
                ('RTN', models.CharField(max_length=15)),
                ('correo', models.EmailField(max_length=100)),
                ('telefono', models.BigIntegerField()),
            ],
            bases=('gestion.inicio',),
        ),
        migrations.CreateModel(
            name='Contribuyente',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gestion.persona')),
                ('numero_expediente', models.IntegerField()),
            ],
            bases=('gestion.persona',),
        ),
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('contribuyente_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gestion.contribuyente')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('nombre_propietario', models.CharField(max_length=100)),
                ('nombre_empresa', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=255)),
                ('clave', models.IntegerField()),
                ('area_terreno', models.IntegerField()),
                ('declaracion', models.FileField(upload_to='documentos/')),
                ('croquis', models.FileField(upload_to='documentos/')),
                ('firma', models.FileField(upload_to='documentos/')),
                ('estado_cuenta', models.FileField(upload_to='documentos/')),
            ],
            bases=('gestion.contribuyente',),
        ),
    ]
