# Generated by Django 5.1.4 on 2024-12-13 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_rename_dni_persona_dni_rename_rtn_persona_rtn'),
    ]

    operations = [
        migrations.CreateModel(
            name='detalleFormularioA',
            fields=[
                ('formulario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gestion.formulario')),
                ('tomo', models.IntegerField()),
                ('numero', models.IntegerField()),
                ('matricula', models.CharField(max_length=50)),
                ('area_terreno_varas', models.IntegerField()),
                ('tipo_obra', models.CharField(max_length=50)),
                ('material', models.CharField(max_length=50)),
                ('tipo_inmueble', models.CharField(max_length=50)),
                ('unidades', models.IntegerField()),
                ('metros_cuadrados', models.IntegerField()),
                ('largo', models.IntegerField()),
                ('alto', models.IntegerField()),
                ('profundidad', models.IntegerField()),
                ('area', models.IntegerField()),
                ('costo_obra', models.CharField(max_length=100)),
                ('corte_arbol', models.BooleanField()),
                ('rotura_via', models.BooleanField()),
                ('solvencia', models.FileField(upload_to='documentos/')),
                ('escritura', models.FileField(upload_to='documentos/')),
                ('constitucion_sociedad', models.FileField(upload_to='documentos/')),
            ],
            bases=('gestion.formulario',),
        ),
        migrations.CreateModel(
            name='detalleFormularioB',
            fields=[
                ('formulario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gestion.formulario')),
                ('rtn_comercial', models.CharField(max_length=15)),
                ('direccion_proyecto', models.CharField(max_length=100)),
                ('zonificacion', models.CharField(max_length=50)),
                ('actividad_realizar', models.CharField(max_length=50)),
                ('nombre_comercial', models.CharField(max_length=50)),
                ('condiciones_operacion', models.CharField(max_length=50)),
                ('tamanio_obra', models.IntegerField()),
                ('area_util_inmueble', models.IntegerField()),
                ('motivo_solicitud_negocio', models.CharField(max_length=15)),
                ('motivo_solicitud_ambiental', models.CharField(max_length=15)),
            ],
            bases=('gestion.formulario',),
        ),
    ]
